"""Actualizar tabla Departamento

Revision ID: 1fd46d1476d0
Revises: b171df22fd76
Create Date: 2024-12-08 19:22:59.016694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd46d1476d0'
down_revision = 'b171df22fd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('num_depto', sa.Integer(), nullable=False),
    sa.Column('nombre_propietario', sa.String(length=50), nullable=False),
    sa.Column('run_propietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_propietario'], ['residente.run'], ),
    sa.PrimaryKeyConstraint('num_depto')
    )
    with op.batch_alter_table('gasto_comun', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'residente', ['residente_id'], ['run'])

    with op.batch_alter_table('residente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('run')

    with op.batch_alter_table('gasto_comun', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'residente', ['residente_id'], ['id'])

    op.drop_table('departamento')
    # ### end Alembic commands ###
