"""Inicializar la base de datos

Revision ID: 4bb29a4ca207
Revises: 
Create Date: 2024-12-08 21:34:43.332814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb29a4ca207'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residente',
    sa.Column('run', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('run'),
    sa.UniqueConstraint('email')
    )
    op.create_table('departamento',
    sa.Column('num_depto', sa.Integer(), nullable=False),
    sa.Column('nombre_propietario', sa.String(length=50), nullable=False),
    sa.Column('run_propietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_propietario'], ['residente.run'], ),
    sa.PrimaryKeyConstraint('num_depto')
    )
    op.create_table('gasto_comun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('residente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['residente_id'], ['residente.run'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('gasto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gasto_id'], ['gasto_comun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pago')
    op.drop_table('gasto_comun')
    op.drop_table('departamento')
    op.drop_table('residente')
    # ### end Alembic commands ###
