"""Agregar tabla Departamento

Revision ID: b025ba69e7ea
Revises: b171df22fd76
Create Date: 2024-12-09 09:47:45.065844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b025ba69e7ea'
down_revision = 'b171df22fd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('num_depto', sa.Integer(), nullable=False),
    sa.Column('nombre_propietario', sa.String(length=50), nullable=False),
    sa.Column('run_propietario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_propietario'], ['residente.id'], ),
    sa.PrimaryKeyConstraint('num_depto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departamento')
    # ### end Alembic commands ###
